modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "easy_homes"
version = "${version}"
displayName = "Easy Homes"
authors = "ivkond"
description = '''
Easy and lightweight /sethome mod
'''
logoFile = "icon.png"

[[dependencies.easy_homes]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_homes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"
