plugins {
    id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}" apply false
    id 'net.neoforged.moddev' version "${moddevgradle_version}" apply false
    id 'com.hypherionmc.modutils.modpublisher' version '2.1.6' apply false
}

allprojects {
    group = rootProject.maven_group
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.archives_name"
    }

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        // For: MidnightLib
        maven { url "https://api.modrinth.com/maven" }
        // For: Xaero's mods
        maven { url 'https://chocolateminecraft.com/maven' }
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 25
    }

    if (enabled_platforms.split(',').contains(project.name)) {
        apply plugin: 'com.hypherionmc.modutils.modpublisher'

        publisher {
            apiKeys {
                modrinth = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN")
                curseforge = project.findProperty("curseforge.token") ?: System.getenv("CURSE_TOKEN")
            }

            setCurseID(curseforge_id)
            setModrinthID(modrinth_id)
            setVersionType("release")
            setChangelog(rootProject.file("./CHANGELOG.md"))
            setGameVersions([minecraft_version])
            setCurseEnvironment("both")
            setArtifact(tasks.named("jar"))
            setJavaVersions([JavaVersion.VERSION_25])
            setDisableEmptyJarCheck(false)
            setLoaders(project.name)
            setProjectVersion("${project.version}")
            setDisplayName("${archives_name}-${project.version}")
        }
    }
}

tasks.register('buildRelease') {
    group 'build'
    dependsOn(':common:build')
    dependsOn(enabled_platforms.split(',').collect {":" + it + ":build" })
}

tasks.register('uploadMod') {
    group 'publishing'
    dependsOn(enabled_platforms.split(',').collect {":" + it + ":publishMod" })
    doLast {
        print("Mods has been successfully uploaded")
    }
}
