# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod platforms
modrinth_id = w4Z2NKqf
curseforge_id = 1163866

# Mod properties
mod_id = easy_homes
mod_version = 21.1.3
mod_name = Easy Homes
mod_author = ivkond
mod_description = Easy and lightweight /sethome mod
mod_sources = https://github.com/ivkond-mc/simple-homes
maven_group = ivkond.md.mods.easy_homes
archives_name = easy_homes
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.16.9
fabric_api_version = 0.110.0+1.21.1
neoforge_version = 21.1.84

# Mods
# https://www.midnightdust.eu/wiki/midnightlib/
midnightlib_version = 1.6.3
# https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap
xaeros_minimap_version = 6012856
