# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod platforms
modrinth_id = w4Z2NKqf
curseforge_id = 1163866

# Mod properties
mod_id = easy_homes
mod_version = 21.4.5
mod_name = Easy Homes
mod_author = ivkond
mod_description = Easy and lightweight /sethome mod
mod_sources = https://github.com/ivkond-mc/simple-homes
maven_group = ivkond.md.mods.easy_homes
archives_name = easy_homes
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4

# Dependencies
fabric_loader_version = 0.16.9
fabric_api_version = 0.112.2+1.21.4
neoforge_version = 21.4.39-beta

# Mods
# https://www.midnightdust.eu/wiki/midnightlib/
midnightlib_version = 1.6.6
xaeros_minimap_version = 6012867
