# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod platforms
modrinth_id = w4Z2NKqf
curseforge_id = 1163866

# Mod properties
mod_id = easy_homes
mod_version = 26.1.2
mod_name = Easy Homes
mod_author = ivkond
mod_description = Easy and lightweight /sethome mod
mod_sources = https://github.com/ivkond-mc/simple-homes
maven_group = ivkond.md.mods.easy_homes
archives_name = easy_homes
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2
minecraft_dependency = ~26.1.2
minecraft_version_range = [26.1.2,)

# Dependencies
fabric_loader_version = 0.19.2
fabric_api_version = 0.150.0+26.1.2
fabric_loom_version = 1.16.3
moddevgradle_version = 2.0.141
neoform_version = 26.1.2-1
neoforge_version = 26.1.2.71
neoforge_version_range = [26.1.2,)

# Mods
# https://www.midnightdust.eu/wiki/midnightlib/
midnightlib_version = 1.9.3+26.1
xaeros_minimap_version = 25.3.14
