pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.firstdark.dev/releases" }
        maven { url "https://maven.neoforged.net/releases" }
        gradlePluginPortal()
    }
}

rootProject.name = 'easy_homes'

include 'common'
include 'fabric'
include 'neoforge'
