plugins {
    id 'net.neoforged.moddev'
}

version = "${rootProject.mod_version}-common"

neoForge {
    neoFormVersion = rootProject.neoform_version
}

dependencies {
    compileOnly "maven.modrinth:midnightlib:${rootProject.midnightlib_version}-fabric"
    compileOnly "xaero.minimap:xaerominimap-common-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_version}"
}
