modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "easy_homes"
version = "${version}"
displayName = "Easy Homes"
authors = "ivkond"
description = '''
Easy and lightweight /sethome mod
'''
#logoFile = ""

[[dependencies.easy_homes]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_homes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "easy_homes.mixins.json"
