plugins {
    id 'net.neoforged.moddev'
}

version = "${rootProject.mod_version}-neoforge"

sourceSets {
    main {
        java.srcDir '../common/src/main/java'
        resources.srcDir '../common/src/main/resources'
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

neoForge {
    version = rootProject.neoforge_version

    mods {
        easy_homes {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    def props = new Properties()
    props.load(new FileReader(rootProject.file('./gradle.properties')))

    inputs.properties props

    filesMatching('META-INF/neoforge.mods.toml') {
        expand props
    }
}

dependencies {
    jarJar(implementation("maven.modrinth:midnightlib:${rootProject.midnightlib_version}-neoforge")) {
        version {
            strictly "[${rootProject.midnightlib_version}-neoforge,)"
            prefer "${rootProject.midnightlib_version}-neoforge"
        }
    }

    compileOnly "xaero.minimap:xaerominimap-common-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_version}"
}
