name: Build and publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish all artifacts into GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_NUMBER: ${{ github.run_number }}

    - name: Read properties
      uses: BrycensRanch/read-properties-action@v1.0.4
      id: gradle_properties
      with:
        file: gradle.properties
        all: true

    # Some weird calculations to simplify publications steps
    - name: Setup environment variables
      run: |
        BUILD_NUMBER=${{ github.run_number }}
        MC_VERSION=${{ steps.gradle_properties.outputs.minecraft_version }}
        MOD_VERSION=${{ steps.gradle_properties.outputs.mod_version }}
        MOD_NAME=${{ steps.gradle_properties.outputs.archives_name }}
        ARTIFACT_VERSION=$MC_VERSION-$MOD_VERSION.$BUILD_NUMBER
        NEOFORGE_JAR_NAME=$MOD_NAME-neoforge-$ARTIFACT_VERSION.jar
        FABRIC_JAR_NAME=$MOD_NAME-fabric-$ARTIFACT_VERSION.jar
        echo "mc_version=$MC_VERSION" >> "$GITHUB_ENV"
        echo "mod_version=$MOD_VERSION" >> "$GITHUB_ENV"
        echo "artifact_version=$ARTIFACT_VERSION" >> "$GITHUB_ENV"
        echo "neoforge_jar_name=$NEOFORGE_JAR_NAME" >> "$GITHUB_ENV"
        echo "neoforge_jar_path=neoforge/build/libs/$NEOFORGE_JAR_NAME" >> "$GITHUB_ENV"
        echo "fabric_jar_name=$FABRIC_JAR_NAME" >> "$GITHUB_ENV"
        echo "fabric_jar=fabric/build/libs/$FABRIC_JAR_NAME" >> "$GITHUB_ENV"

    - name: Publish NeoForge artifact
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ steps.gradle_properties.outputs.modrith_id }}
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: ${{ steps.gradle_properties.outputs.curseforge_id }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

        files: ${{ env.neoforge_jar_path }}
        name: ${{ env.neoforge_jar_name }}
        version: ${{ env.artifact_version }}
        version-type: release

        loaders: neoforge
        game-versions: ${{ env.mc_version }}
        game-version-filter: none
        java: 21

        retry-attempts: 2
        retry-delay: 10000
        fail-mode: fail

    - name: Publish Fabric artifact
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ steps.gradle_properties.outputs.modrith_id }}
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: ${{ steps.gradle_properties.outputs.curseforge_id }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

        files: ${{ env.fabric_jar_path }}
        name: ${{ env.fabric_jar_name }}
        version: ${{ env.artifact_version }}
        version-type: release

        loaders: fabric
        game-versions: ${{ env.mc_version }}
        game-version-filter: none
        dependencies: |
          modmenu@11.0.3(optional){modrinth:YIfqIJ8q}{curseforge:308702}
        java: 21

        retry-attempts: 2
        retry-delay: 10000
        fail-mode: fail
